CREATE TABLE images (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(100) NOT NULL,
    doc_id INT(11) UNSIGNED NOT NULL,

    FOREIGN KEY (doc_id) REFERENCES image_docs(id) ON DELETE CASCADE
);