CREATE TABLE file_docs (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(400) NULL,
    category_id INT(11) UNSIGNED NOT NULL,
    file_path VARCHAR(150) NOT NULL,
    file_name VARCHAR(150) NOT NULL,
    file_weight INT NOT NULL,
    file_extension VARCHAR(10) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);